<?php
/**
 * أداة النسخ الاحتياطي لقاعدة البيانات
 * Database Backup Tool
 *
 * ميزات:
 * - نسخ احتياطي تلقائي
 * - ضغط البيانات
 * - جدولة النسخ
 * - استعادة البيانات
 * - تنظيف النسخ القديمة
 */

session_start();
require 'db.php';

if (!isset($_SESSION['user_id'])) {
    header("Location: login.php");
    exit;
}

// التحقق من الصلاحيات - فقط المدير والمسؤول يمكنهم الوصول
if (!in_array($_SESSION['permissions'], ['admin', 'manager'])) {
    header("Location: index.php?error=access_denied");
    exit;
}

class DatabaseBackup
{
    private $pdo;
    private $backupDir;

    public function __construct($pdo)
    {
        $this->pdo = $pdo;
        $this->backupDir = __DIR__ . '/backups/';

        // إنشاء مجلد النسخ الاحتياطية إذا لم يكن موجوداً
        if (!is_dir($this->backupDir)) {
            mkdir($this->backupDir, 0755, true);
        }
    }

    /**
     * إنشاء نسخة احتياطية
     */
    public function createBackup($compress = true, $includeData = true)
    {
        $timestamp = date('Y-m-d_H-i-s');
        $filename = "backup_{$timestamp}.sql";
        $filepath = $this->backupDir . $filename;

        try {
            // الحصول على قائمة الجداول
            $tables = $this->pdo->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);

            $sql = "-- Database Backup Created: " . date('Y-m-d H:i:s') . "\n";
            $sql .= "-- Generated by Device Management System\n\n";
            $sql .= "SET SQL_MODE = \"NO_AUTO_VALUE_ON_ZERO\";\n";
            $sql .= "START TRANSACTION;\n\n";

            foreach ($tables as $table) {
                // هيكل الجدول
                $sql .= "-- Table structure for `$table`\n";
                $createTable = $this->pdo->query("SHOW CREATE TABLE `$table`")->fetch(PDO::FETCH_ASSOC);
                $sql .= $createTable['Create Table'] . ";\n\n";

                if ($includeData) {
                    // بيانات الجدول
                    $rows = $this->pdo->query("SELECT * FROM `$table`")->fetchAll(PDO::FETCH_ASSOC);

                    if (!empty($rows)) {
                        $sql .= "-- Data for `$table`\n";
                        foreach ($rows as $row) {
                            $values = array_map([$this, 'escapeValue'], array_values($row));
                            $sql .= "INSERT INTO `$table` VALUES (" . implode(', ', $values) . ");\n";
                        }
                        $sql .= "\n";
                    }
                }
            }

            $sql .= "COMMIT;\n";

            // كتابة الملف
            if ($compress) {
                $gzFilepath = $filepath . '.gz';
                $gz = gzopen($gzFilepath, 'w9');
                gzwrite($gz, $sql);
                gzclose($gz);
                return [
                    'success' => true,
                    'file' => basename($gzFilepath),
                    'size' => filesize($gzFilepath),
                    'path' => $gzFilepath
                ];
            } else {
                file_put_contents($filepath, $sql);
                return [
                    'success' => true,
                    'file' => $filename,
                    'size' => filesize($filepath),
                    'path' => $filepath
                ];
            }

        } catch (Exception $e) {
            return [
                'success' => false,
                'error' => $e->getMessage()
            ];
        }
    }

    /**
     * استعادة نسخة احتياطية
     */
    public function restoreBackup($filepath)
    {
        try {
            // قراءة محتوى الملف
            if (pathinfo($filepath, PATHINFO_EXTENSION) === 'gz') {
                $content = gzread(gzopen($filepath, 'r'), filesize($filepath));
            } else {
                $content = file_get_contents($filepath);
            }

            // تنفيذ الاستعلامات
            $this->pdo->exec($content);

            return [
                'success' => true,
                'message' => 'تم استعادة النسخة الاحتياطية بنجاح'
            ];

        } catch (Exception $e) {
            return [
                'success' => false,
                'error' => 'خطأ في استعادة النسخة: ' . $e->getMessage()
            ];
        }
    }

    /**
     * جلب قائمة النسخ الاحتياطية
     */
    public function getBackupList()
    {
        $files = glob($this->backupDir . '*.{sql,sql.gz}', GLOB_BRACE);

        $backups = [];
        foreach ($files as $file) {
            $filename = basename($file);
            $backups[] = [
                'filename' => $filename,
                'filepath' => $file,
                'size' => filesize($file),
                'created' => filemtime($file),
                'formatted_size' => $this->formatBytes(filesize($file)),
                'formatted_date' => date('Y-m-d H:i:s', filemtime($file)),
                'is_compressed' => pathinfo($file, PATHINFO_EXTENSION) === 'gz'
            ];
        }

        // ترتيب حسب التاريخ (الأحدث أولاً)
        usort($backups, function($a, $b) {
            return $b['created'] - $a['created'];
        });

        return $backups;
    }

    /**
     * حذف نسخة احتياطية
     */
    public function deleteBackup($filename)
    {
        $filepath = $this->backupDir . $filename;

        if (file_exists($filepath)) {
            unlink($filepath);
            return ['success' => true];
        }

        return ['success' => false, 'error' => 'الملف غير موجود'];
    }

    /**
     * تنظيف النسخ القديمة
     */
    public function cleanupOldBackups($days = 30)
    {
        $files = glob($this->backupDir . '*.{sql,sql.gz}', GLOB_BRACE);
        $deleted = 0;

        foreach ($files as $file) {
            if (filemtime($file) < time() - ($days * 24 * 60 * 60)) {
                unlink($file);
                $deleted++;
            }
        }

        return ['deleted' => $deleted];
    }

    /**
     * جلب إحصائيات قاعدة البيانات
     */
    public function getDatabaseStats()
    {
        try {
            // عدد الجداول
            $tables = $this->pdo->query("SHOW TABLES")->fetchAll(PDO::FETCH_COLUMN);
            $tableCount = count($tables);

            // حجم قاعدة البيانات
            $dbSize = $this->pdo->query("
                SELECT ROUND(SUM(data_length + index_length) / 1024 / 1024, 2) as size_mb
                FROM information_schema.TABLES
                WHERE table_schema = DATABASE()
            ")->fetch(PDO::FETCH_ASSOC);

            // عدد السجلات في كل جدول
            $tableStats = [];
            foreach ($tables as $table) {
                $count = $this->pdo->query("SELECT COUNT(*) FROM `$table`")->fetchColumn();
                $tableStats[$table] = $count;
            }

            return [
                'success' => true,
                'table_count' => $tableCount,
                'database_size' => $dbSize['size_mb'] ?? 0,
                'table_stats' => $tableStats,
                'total_records' => array_sum($tableStats)
            ];

        } catch (Exception $e) {
            return [
                'success' => false,
                'error' => $e->getMessage()
            ];
        }
    }

    /**
     * دوال مساعدة
     */
    private function escapeValue($value)
    {
        if ($value === null) {
            return 'NULL';
        }

        if (is_numeric($value)) {
            return $value;
        }

        return $this->pdo->quote($value);
    }

    private function formatBytes($bytes)
    {
        $units = ['B', 'KB', 'MB', 'GB'];
        $i = 0;

        while ($bytes >= 1024 && $i < count($units) - 1) {
            $bytes /= 1024;
            $i++;
        }

        return round($bytes, 2) . ' ' . $units[$i];
    }
}

// معالجة الطلبات AJAX
if (isset($_GET['action'])) {
    header('Content-Type: application/json');
    $backup = new DatabaseBackup($pdo);

    switch ($_GET['action']) {
        case 'create_backup':
            $compress = isset($_GET['compress']) ? (bool)$_GET['compress'] : true;
            $includeData = isset($_GET['include_data']) ? (bool)$_GET['include_data'] : true;
            echo json_encode($backup->createBackup($compress, $includeData));
            break;

        case 'restore_backup':
            if (isset($_POST['filepath'])) {
                echo json_encode($backup->restoreBackup($_POST['filepath']));
            }
            break;

        case 'delete_backup':
            if (isset($_POST['filename'])) {
                echo json_encode($backup->deleteBackup($_POST['filename']));
            }
            break;

        case 'cleanup':
            $days = isset($_POST['days']) ? (int)$_POST['days'] : 30;
            echo json_encode($backup->cleanupOldBackups($days));
            break;

        case 'get_stats':
            echo json_encode($backup->getDatabaseStats());
            break;
    }
    exit;
}

// جلب البيانات الأولية
$backup = new DatabaseBackup($pdo);
$backups = $backup->getBackupList();
$dbStats = $backup->getDatabaseStats();

?>

<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>إدارة النسخ الاحتياطية - نظام الصيانة</title>

    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700&display=swap" rel="stylesheet">

    <style>
        body { font-family: 'Cairo', sans-serif; }
        .animate-fade-in { animation: fadeIn 0.5s ease-in-out; }
        .backup-card { transition: all 0.3s ease; }
        .backup-card:hover { transform: translateY(-2px); box-shadow: 0 10px 20px rgba(0,0,0,0.1); }
        .progress-bar { transition: width 0.3s ease; }

        @keyframes fadeIn {
            from { opacity: 0; transform: translateY(20px); }
            to { opacity: 1; transform: translateY(0); }
        }

        .loading-overlay {
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            background: rgba(255, 255, 255, 0.9);
            display: flex;
            align-items: center;
            justify-content: center;
            z-index: 9999;
        }
    </style>
</head>
<body class="bg-gray-50" x-data="backupManager()">

    <!-- Loading Overlay -->
    <div x-show="isLoading" class="loading-overlay" x-transition>
        <div class="text-center">
            <div class="animate-spin rounded-full h-16 w-16 border-b-2 border-blue-600 mx-auto mb-4"></div>
            <p class="text-lg font-semibold text-gray-700" x-text="loadingMessage"></p>
        </div>
    </div>

    <div class="container mx-auto p-4 sm:p-6 lg:p-8 max-w-6xl">

        <!-- Header -->
        <div class="flex justify-between items-center mb-8">
            <div>
                <h1 class="text-3xl font-bold text-gray-800 mb-2">إدارة النسخ الاحتياطية</h1>
                <p class="text-gray-600">إنشاء وإدارة النسخ الاحتياطية لقاعدة البيانات</p>
            </div>
            <div class="flex items-center gap-4">
                <a href="index.php" class="text-blue-600 hover:text-blue-800 flex items-center gap-2">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path>
                    </svg>
                    العودة للرئيسية
                </a>
            </div>
        </div>

        <!-- إحصائيات قاعدة البيانات -->
        <div class="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
            <div class="bg-white rounded-xl shadow-lg p-6 animate-fade-in">
                <div class="flex items-center justify-between">
                    <div>
                        <p class="text-gray-600 text-sm">عدد الجداول</p>
                        <p class="text-2xl font-bold text-blue-600" x-text="dbStats.table_count || 0"></p>
                    </div>
                    <div class="p-3 bg-blue-100 rounded-full">
                        <svg class="w-8 h-8 text-blue-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path>
                        </svg>
                    </div>
                </div>
            </div>

            <div class="bg-white rounded-xl shadow-lg p-6 animate-fade-in">
                <div class="flex items-center justify-between">
                    <div>
                        <p class="text-gray-600 text-sm">حجم قاعدة البيانات</p>
                        <p class="text-2xl font-bold text-green-600" x-text="(dbStats.database_size || 0) + ' MB'"></p>
                    </div>
                    <div class="p-3 bg-green-100 rounded-full">
                        <svg class="w-8 h-8 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 12h14M5 12a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v4a2 2 0 01-2 2M5 12a2 2 0 00-2 2v4a2 2 0 002 2h14a2 2 0 002-2v-4a2 2 0 00-2-2m-2-4h.01M17 16h.01"></path>
                        </svg>
                    </div>
                </div>
            </div>

            <div class="bg-white rounded-xl shadow-lg p-6 animate-fade-in">
                <div class="flex items-center justify-between">
                    <div>
                        <p class="text-gray-600 text-sm">إجمالي السجلات</p>
                        <p class="text-2xl font-bold text-purple-600" x-text="(dbStats.total_records || 0).toLocaleString()"></p>
                    </div>
                    <div class="p-3 bg-purple-100 rounded-full">
                        <svg class="w-8 h-8 text-purple-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 12l3-3 3 3 4-4M8 21l4-4 4 4M3 4h18M4 4h16v12a1 1 0 01-1 1H5a1 1 0 01-1-1V4z"></path>
                        </svg>
                    </div>
                </div>
            </div>

            <div class="bg-white rounded-xl shadow-lg p-6 animate-fade-in">
                <div class="flex items-center justify-between">
                    <div>
                        <p class="text-gray-600 text-sm">عدد النسخ</p>
                        <p class="text-2xl font-bold text-orange-600" x-text="backups.length"></p>
                    </div>
                    <div class="p-3 bg-orange-100 rounded-full">
                        <svg class="w-8 h-8 text-orange-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                        </svg>
                    </div>
                </div>
            </div>
        </div>

        <!-- أدوات النسخ الاحتياطي -->
        <div class="bg-white rounded-xl shadow-lg p-6 mb-8 animate-fade-in">
            <h3 class="text-xl font-bold text-gray-800 mb-6">إنشاء نسخة احتياطية جديدة</h3>

            <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
                <div class="space-y-4">
                    <label class="flex items-center">
                        <input type="checkbox" x-model="backupOptions.compress" class="rounded border-gray-300 text-blue-600">
                        <span class="mr-2 text-sm text-gray-700">ضغط الملف (GZ)</span>
                    </label>
                    <label class="flex items-center">
                        <input type="checkbox" x-model="backupOptions.includeData" class="rounded border-gray-300 text-blue-600">
                        <span class="mr-2 text-sm text-gray-700">تضمين البيانات</span>
                    </label>
                </div>

                <div class="flex items-end">
                    <button @click="createBackup()"
                            :disabled="isCreating"
                            class="w-full bg-gradient-to-r from-blue-600 to-purple-600 text-white py-3 px-6 rounded-lg hover:from-blue-700 hover:to-purple-700 disabled:opacity-50 flex items-center justify-center gap-2">
                        <svg x-show="!isCreating" class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                        </svg>
                        <svg x-show="isCreating" class="w-5 h-5 animate-spin" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"></path>
                        </svg>
                        <span x-text="isCreating ? 'جاري الإنشاء...' : 'إنشاء نسخة احتياطية'"></span>
                    </button>
                </div>

                <div class="flex items-end">
                    <button @click="cleanupOldBackups()"
                            class="w-full bg-red-600 text-white py-3 px-6 rounded-lg hover:bg-red-700 flex items-center justify-center gap-2">
                        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
                        </svg>
                        تنظيف النسخ القديمة
                    </button>
                </div>
            </div>
        </div>

        <!-- قائمة النسخ الاحتياطية -->
        <div class="bg-white rounded-xl shadow-lg p-6 animate-fade-in">
            <div class="flex justify-between items-center mb-6">
                <h3 class="text-xl font-bold text-gray-800">النسخ الاحتياطية المتاحة</h3>
                <button @click="refreshBackups()" class="text-blue-600 hover:text-blue-800 flex items-center gap-2">
                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"></path>
                    </svg>
                    تحديث
                </button>
            </div>

            <div x-show="backups.length === 0" class="text-center py-12">
                <svg class="w-16 h-16 text-gray-300 mx-auto mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                </svg>
                <p class="text-gray-500 text-lg">لا توجد نسخ احتياطية متاحة</p>
                <p class="text-gray-400 text-sm">قم بإنشاء نسخة احتياطية جديدة للبدء</p>
            </div>

            <div class="space-y-4" x-show="backups.length > 0">
                <template x-for="(backup, index) in backups" :key="backup.filename">
                    <div class="backup-card border border-gray-200 rounded-lg p-4 hover:border-blue-300">
                        <div class="flex items-center justify-between">
                            <div class="flex-1">
                                <div class="flex items-center gap-3 mb-2">
                                    <h4 class="font-semibold text-gray-800" x-text="backup.filename"></h4>
                                    <span x-show="backup.is_compressed" class="px-2 py-1 bg-green-100 text-green-700 text-xs rounded-full">
                                        مضغوط
                                    </span>
                                </div>
                                <div class="flex items-center gap-6 text-sm text-gray-600">
                                    <span class="flex items-center gap-1">
                                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M8 7V3a2 2 0 012-2h4a2 2 0 012 2v4m-6 4v10a2 2 0 002 2h4a2 2 0 002-2V11M9 11h6"></path>
                                        </svg>
                                        <span x-text="backup.formatted_size"></span>
                                    </span>
                                    <span class="flex items-center gap-1">
                                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z"></path>
                                        </svg>
                                        <span x-text="backup.formatted_date"></span>
                                    </span>
                                </div>
                            </div>
                            <div class="flex items-center gap-2">
                                <button @click="downloadBackup(backup.filename)"
                                        class="p-2 text-blue-600 hover:bg-blue-50 rounded-lg" title="تحميل">
                                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
                                    </svg>
                                </button>
                                <button @click="restoreBackup(backup.filepath, backup.filename)"
                                        class="p-2 text-green-600 hover:bg-green-50 rounded-lg" title="استعادة">
                                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"></path>
                                    </svg>
                                </button>
                                <button @click="deleteBackup(backup.filename)"
                                        class="p-2 text-red-600 hover:bg-red-50 rounded-lg" title="حذف">
                                    <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
                                    </svg>
                                </button>
                            </div>
                        </div>
                    </div>
                </template>
            </div>
        </div>
    </div>

    <script>
        document.addEventListener('alpine:init', () => {
            Alpine.data('backupManager', () => ({
                backups: <?php echo json_encode($backups); ?>,
                dbStats: <?php echo json_encode($dbStats); ?>,
                isLoading: false,
                loadingMessage: '',
                isCreating: false,
                backupOptions: {
                    compress: true,
                    includeData: true
                },

                async createBackup() {
                    this.isCreating = true;
                    this.loadingMessage = 'جاري إنشاء النسخة الاحتياطية...';

                    try {
                        const response = await fetch('database_backup.php?action=create_backup&compress=' + this.backupOptions.compress + '&include_data=' + this.backupOptions.includeData);
                        const result = await response.json();

                        if (result.success) {
                            await Swal.fire({
                                icon: 'success',
                                title: 'تم إنشاء النسخة الاحتياطية',
                                html: `
                                    <div class="text-center">
                                        <p class="mb-2">تم إنشاء النسخة بنجاح</p>
                                        <p class="text-sm text-gray-600">الملف: <strong>${result.file}</strong></p>
                                        <p class="text-sm text-gray-600">الحجم: <strong>${this.formatBytes(result.size)}</strong></p>
                                    </div>
                                `
                            });
                            await this.refreshBackups();
                        } else {
                            throw new Error(result.error || 'حدث خطأ غير معروف');
                        }
                    } catch (error) {
                        await Swal.fire({
                            icon: 'error',
                            title: 'خطأ في إنشاء النسخة',
                            text: error.message
                        });
                    } finally {
                        this.isCreating = false;
                    }
                },

                async restoreBackup(filepath, filename) {
                    const result = await Swal.fire({
                        title: 'تأكيد الاستعادة',
                        html: `
                            <div class="text-center">
                                <p class="mb-4">هل أنت متأكد من استعادة النسخة الاحتياطية؟</p>
                                <p class="text-sm text-red-600 bg-red-50 p-3 rounded-lg">
                                    ⚠️ تحذير: هذا الإجراء سيستبدل جميع البيانات الحالية
                                </p>
                                <p class="text-sm text-gray-600 mt-2">الملف: <strong>${filename}</strong></p>
                            </div>
                        `,
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonText: 'نعم، استعادة',
                        cancelButtonText: 'إلغاء',
                        confirmButtonColor: '#d33',
                        cancelButtonColor: '#3085d6'
                    });

                    if (!result.isConfirmed) return;

                    this.isLoading = true;
                    this.loadingMessage = 'جاري استعادة النسخة الاحتياطية...';

                    try {
                        const formData = new FormData();
                        formData.append('filepath', filepath);

                        const response = await fetch('database_backup.php?action=restore_backup', {
                            method: 'POST',
                            body: formData
                        });
                        const data = await response.json();

                        if (data.success) {
                            await Swal.fire({
                                icon: 'success',
                                title: 'تمت الاستعادة بنجاح',
                                text: 'تم استعادة النسخة الاحتياطية بنجاح'
                            });
                            // إعادة تحميل الصفحة
                            window.location.reload();
                        } else {
                            throw new Error(data.error || 'حدث خطأ في الاستعادة');
                        }
                    } catch (error) {
                        await Swal.fire({
                            icon: 'error',
                            title: 'خطأ في الاستعادة',
                            text: error.message
                        });
                    } finally {
                        this.isLoading = false;
                    }
                },

                async deleteBackup(filename) {
                    const result = await Swal.fire({
                        title: 'تأكيد الحذف',
                        text: `هل أنت متأكد من حذف النسخة الاحتياطية "${filename}"؟`,
                        icon: 'warning',
                        showCancelButton: true,
                        confirmButtonText: 'نعم، حذف',
                        cancelButtonText: 'إلغاء',
                        confirmButtonColor: '#d33'
                    });

                    if (!result.isConfirmed) return;

                    try {
                        const formData = new FormData();
                        formData.append('filename', filename);

                        const response = await fetch('database_backup.php?action=delete_backup', {
                            method: 'POST',
                            body: formData
                        });
                        const data = await response.json();

                        if (data.success) {
                            await Swal.fire({
                                icon: 'success',
                                title: 'تم الحذف',
                                text: 'تم حذف النسخة الاحتياطية بنجاح'
                            });
                            await this.refreshBackups();
                        } else {
                            throw new Error(data.error || 'حدث خطأ في الحذف');
                        }
                    } catch (error) {
                        await Swal.fire({
                            icon: 'error',
                            title: 'خطأ في الحذف',
                            text: error.message
                        });
                    }
                },

                async cleanupOldBackups() {
                    const result = await Swal.fire({
                        title: 'تنظيف النسخ القديمة',
                        input: 'number',
                        inputLabel: 'حذف النسخ الأقدم من (أيام):',
                        inputValue: 30,
                        inputAttributes: {
                            min: 1,
                            max: 365
                        },
                        showCancelButton: true,
                        confirmButtonText: 'تنظيف',
                        cancelButtonText: 'إلغاء'
                    });

                    if (!result.isConfirmed) return;

                    try {
                        const formData = new FormData();
                        formData.append('days', result.value);

                        const response = await fetch('database_backup.php?action=cleanup', {
                            method: 'POST',
                            body: formData
                        });
                        const data = await response.json();

                        await Swal.fire({
                            icon: 'success',
                            title: 'تم التنظيف',
                            text: `تم حذف ${data.deleted} نسخة احتياطية قديمة`
                        });
                        await this.refreshBackups();
                    } catch (error) {
                        await Swal.fire({
                            icon: 'error',
                            title: 'خطأ في التنظيف',
                            text: error.message
                        });
                    }
                },

                async refreshBackups() {
                    const response = await fetch('database_backup.php?action=get_stats');
                    const stats = await response.json();
                    if (stats.success) {
                        this.dbStats = stats;
                    }

                    // إعادة تحميل قائمة النسخ
                    const backupResponse = await fetch(window.location.href);
                    const html = await backupResponse.text();
                    // استخراج البيانات من HTML (يمكن تحسين هذا)
                    window.location.reload();
                },

                downloadBackup(filename) {
                    const link = document.createElement('a');
                    link.href = `backups/${filename}`;
                    link.download = filename;
                    document.body.appendChild(link);
                    link.click();
                    document.body.removeChild(link);
                },

                formatBytes(bytes) {
                    if (bytes === 0) return '0 B';
                    const k = 1024;
                    const sizes = ['B', 'KB', 'MB', 'GB'];
                    const i = Math.floor(Math.log(bytes) / Math.log(k));
                    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
                }
            }));
        });
    </script>

</body>
</html>